debug: false

# CDC cursor: file or redis
progress:
  type: file
  path: data/progress.json

# Source: postgres | mysql | mongo
source:
  type: postgres
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: "postgres"
  database: postgres

meilisearch:
  api_url: http://127.0.0.1:7700
  api_key: "MASTER_KEY"
  insert_size: 1000
  insert_interval: 5

sync:
  - table: table_name
    index: index_name
    pk: id
    full: true
    fields:
      id:
      title:

# Optional
# sentry:
#   dsn: ""
#   environment: production
